### ISSUE TITLE
Makefile is confused with Scala

### ISSUE THREAD

**Issue by rns** [github/linguist#1988]
The language of this [makefile](https://github.com/rns/libmarpa-bindings/blob/master/c%23/Makefile) is misdetermined [as Scala](https://github.com/rns/libmarpa-bindings/search?l=scala).

**Comment by pchaigno** [comment]
#2006 should fix this.

**Comment by rns** [comment]
Hmm, that makefile still shown as Scala -- https://github.com/rns/libmarpa-bindings/search?l=scala -- need to wait for update?

**Comment by pchaigno** [comment]
@rns You will have to wait for the next release with the PR merged ;) (usually every couple weeks).

**Comment by rns** [comment]
Thanks, I gladly will. : )

**Comment by arfon** [comment]
Fixed a while back.
