### ISSUE TITLE
C# Misidentified As Smalltalk

### ISSUE THREAD

**Issue by martincostello** [github/linguist#2012]
Within the last month or so (I'm not sure of the exact date), the code in my repo has changed from being identified as 100% C# to 96% C# and 4% Smalltalk. All of the files identified as Smalltalk are in fact C#.

The specific results can be seen [here](https://github.com/martincostello/sqllocaldb/search?l=smalltalk).

It would appear that the mis-identification is happening on files that contain no methods (i.e. only attributes, fields, properties etc.).

**Comment by arfon** [comment]
Hi @martincostello, thanks for reporting this. We have a fix merged into master for this: https://github.com/github/linguist/pull/2003 and expect this change to be live in the next few days.

**Comment by martincostello** [comment]
Great, thanks.

I did try and see if there was an open issue against this, but as it had already been closed so I missed it :)

**Comment by am11** [comment]
@arfon, on [dotnet/corefx](https://github.com/dotnet/corefx/) repo, it still shows "SmallTalk 34.8%" and when we click on it, [it shows](https://github.com/dotnet/corefx/search?l=smalltalk):
`We couldn't find any code matching ''`.

**Comment by JamesFaix** [comment]
I'm seeing the same issue as @martincostello: 4% of C# is interpreted as Smalltalk. https://github.com/JamesFaix/Traction
