### ISSUE TITLE
A dot at the end of file name

### ISSUE THREAD

**Issue by vflyson** [github/linguist#3348]
Hello.

I have a couple of files in one of my repositories which represent plain-text files containing song lyrics instead of code.
There is no file name extension, just song names. Some have names such as "B.Y.O.B." and "L.I.F.E." which `linguist` wrongfully recognizes by treating their last letters as extensions, ignoring the final period following the letter.
Here they are:
 - https://github.com/Lyrics/lyrics/search?l=objective-c
 - https://github.com/Lyrics/lyrics/search?l=brainfuck
 - https://github.com/Lyrics/lyrics/search?l=eiffel
 - https://github.com/Lyrics/lyrics/search?l=yacc
 - https://github.com/Lyrics/lyrics/search?l=rebol
 - https://github.com/Lyrics/lyrics/search?l=groff

I would not count this as a bug and it is not a big deal at all, but at the same time having a period after the extension being ignored seems like something that could be considered an inconsistency.
Having a file name made solely out of a file name extension is also less likely than having a hidden file with no name and only extension for its name, hence I believe it's something that you may want to look at.

Thank you.

**Comment by pchaigno** [comment]
Thanks @vflyson for reporting this!
#3349 should fix it.

**Comment by vflyson** [comment]
Hello again.

Not sure if I should open a new issue or post here so will go with the latter first.

I'm still having issues with linguist wrongfully recognizing filenames made up only out of an extension or which have a dot at the end:
https://github.com/Lyrics/lyrics/search?l=Yacc
https://github.com/Lyrics/lyrics/search?l=Roff
https://github.com/Lyrics/lyrics/search?l=Objective-C

Thanks.

**Comment by pchaigno** [comment]
Here's what I get if I run Linguist against your repository locally:
```
$ linguist --breakdown
83.37%  R
16.63%  Roff

R:
database/A/Architects/Lost Forever ∕∕ Lost Together/C.A.N.C.E.R

Roff:
database/P/Porcupine Tree/In Absentia/.3
```
Those are expected results since `R` and `3` are R and Roff extensions. Other misclassifed files on your repository are probably the result of outdated Linguist results (they usually update with every new push to the repository).
@brandonblack Would it be possible to manually trigger an update of statistics for https://github.com/Lyrics/lyrics?

**Comment by vflyson** [comment]
Ah, that makes sense.
I will force-push those files again then, thanks!
